# Generated by Django 2.2.4 on 2020-01-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('oily', models.SmallIntegerField()),
                ('dry', models.SmallIntegerField()),
                ('sensitive', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('monthlySales', models.IntegerField()),
            ],
        ),
    ]
